export const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 2848 },
    items: 5,
    slidesToSlide: 2,
  },
  desktop: { 
    breakpoint: { max: 2848, min: 1524 },
    items: 5,
  },
  desktop2: {
    breakpoint: { max: 1524, min: 900},
    items: 4,
  },
  desktop1: {
    breakpoint: { max: 900, min: 600 },
    items: 3,
  },
  tablet: {
    breakpoint: { max: 600, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};

export const KerlaData = [
  {
    id: 1,
    name: "Premium 5N Trip to Kerla",
    imageurl: "images/assets/packages/kerla.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "4N/5D",
    price: "Rs. 35,598",
  },
  {
    id: 2,
    name: "Marvellous Kerla",
    imageurl: "images/assets/packages/thailand.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "5N/6D",
    price: "Rs. 23,798",
  },
  {
    id: 3,
    name: "Scenic Kerla Holiday",
    imageurl: "images/assets/packages/thailand.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "6N/7D",
    price: "Rs. 32,255",
  },
  {
    id: 4,
    name: "Facinating Kerla with Alleppey",
    imageurl: "images/assets/packages/ladakh.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "7N/8D",
    price: "Rs. 38,158",
  },
  {
    id: 5,
    name: "Glorious Wayanad & Munnar",
    imageurl: "images/assets/packages/bali.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "8N/9D",
    price: "Rs. 55,522",
  },
  {
    id: 6,
    name: "Glorious Wayanad & Munnar",
    imageurl: "images/assets/packages/bali.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "9N/10D",
    price: "Rs. 55,522",
  },
];
