export const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 2848 },
    items: 5,
    slidesToSlide: 2,
  },
  desktop: {
    breakpoint: { max: 2848, min: 1524 },
    items: 5,
  },
  desktop2: {
    breakpoint: { max: 1524, min: 900 },
    items: 4,
  },
  desktop1: {
    breakpoint: { max: 900, min: 600 },
    items: 3,
  },
  tablet: {
    breakpoint: { max: 600, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};

export const NationalPackagesData = [
  {
    id: 1,
    name: "Kerla",
    imageurl: "images/assets/packages/kerla.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "4N/5D",
    old_price: "Rs. 35,598",
    new_price: "Rs. 30,000",
    link: "/KerlaOffer",
  },
  {
    id: 2,
    name: "Goa",
    imageurl: "images/assets/packages/goa.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "5N/6D",
    old_price: "Rs. 45,598",
    new_price: "Rs. 40,000",
    link: "/KerlaOffer",
  },
  {
    id: 3,
    name: "Ladakh",
    imageurl: "images/assets/packages/ladakh.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "6N/7D",
    old_price: "Rs. 25,598",
    new_price: "Rs. 20,000",
    link: "/KerlaOffer",
  },
  {
    id: 4,
    name: "Ooty",
    imageurl: "images/assets/packages/ooty.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "7N/8D",
    old_price: "Rs. 55,598",
    new_price: "Rs. 50,000",
    link: "/KerlaOffer",
  },
  {
    id: 5,
    name: "Banglore",
    imageurl: "images/assets/packages/goa.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "8N/9D",
    old_price: "Rs. 35,598",
    new_price: "Rs. 30,000",
    link: "/KerlaOffer",
  },
  {
    id: 6,
    name: "Kashmir",
    imageurl: "images/assets/packages/kashmir.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "8N/9D",
    old_price: "Rs. 35,598",
    new_price: "Rs. 30,000",
    link: "/KerlaOffer",
  },
  {
    id: 7,
    name: "Rajasthan",
    imageurl: "images/assets/packages/rajasthan.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "8N/9D",
    old_price: "Rs. 35,598",
    new_price: "Rs. 30,000",
    link: "/KerlaOffer",
  },
  {
    id: 8,
    name: "Delhi",
    imageurl: "images/assets/packages/delhi.jpg",
    facility1: "2Flights",
    facility2: "3Hotels",
    facility3: "7Activities",
    facility4: "6Transfers",
    days: "8N/9D",
    old_price: "Rs. 35,598",
    new_price: "Rs. 30,000",
    link: "/KerlaOffer",
  },
];
